import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv()

def format_as_html(problems_json, date_str):
    """Wraps the JSON data in a beautiful HTML template."""
    import json
    try:
        problems = json.loads(problems_json.strip('`').replace('json\n', ''))
    except:
        return f"Error parsing JSON: {problems_json}"

    problem_blocks = ""
    colors = ["#E74C3C", "#3498DB", "#F1C40F", "#2ECC71", "#9B59B6"]
    
    for i, p in enumerate(problems):
        color = colors[i % len(colors)]
        
        # Handle features safely (ensure it's a list)
        features_raw = p.get('features', [])
        if isinstance(features_raw, str):
            features_list_items = [features_raw]
        else:
            features_list_items = features_raw
            
        features_html = "".join([f"<li>{f}</li>" for f in features_list_items])
        
        problem_blocks += f"""
        <div style="border: 1px solid #ddd; border-left: 8px solid {color}; padding: 20px; margin-bottom: 30px; border-radius: 8px; background-color: #fcfcfc;">
            <h2 style="color: {color}; margin-top: 0;">🔥 PROBLEM #{i+1}: {p['title']}</h2>
            <p style="font-weight: bold; color: #555;">📍 समाधान क्यों ज़रूरी है? (The Reality):</p>
            <p>{p['is_real_problem']}</p>
            
            <div style="background-color: #fff; padding: 15px; border-radius: 5px; margin: 15px 0; border: 1px solid #eee;">
                <p><strong>गहराई से विवरण:</strong> {p['description']}</p>
                <p><strong>डेटा और प्रभाव:</strong> <span style="color: #E67E22;">{p['impact']}</span></p>
                <p><strong>क्यों सरकारी/NGO समाधान असफल हैं?</strong> {p['why_failed']}</p>
            </div>

            <div style="background-color: #f0f7ff; padding: 15px; border-radius: 5px; border-left: 4px solid #2980b9;">
                <h3 style="margin-top: 0; color: #2980b9;">💡 STARTUP IDEA: {p['startup_idea']}</h3>
                <p><strong>Tech Logic:</strong> {p['tech_solution']}</p>
                <p><strong>Key Features:</strong></p>
                <ul>{features_html}</ul>
                <p><strong>Scalability:</strong> {p['scalability']}</p>
                <p><strong>Market Size (Revenue):</strong> <span style="font-size: 1.2em; font-weight: bold; color: #27ae60;">₹{p['market_size']} Crore</span></p>
            </div>
        </div>
        """

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f4f4f4; }}
            .container {{ background-color: #fff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }}
            .header {{ text-align: center; border-bottom: 3px solid #eee; padding-bottom: 20px; margin-bottom: 30px; }}
            .footer {{ font-size: 0.8em; color: #7f8c8d; text-align: center; margin-top: 40px; border-top: 1px solid #eee; padding-top: 20px; }}
            .badge {{ background-color: #2c3e50; color: #fff; padding: 5px 12px; border-radius: 20px; font-size: 0.9em; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1 style="color: #2c3e50; margin-bottom: 5px;">🚀 दैनिक स्टार्टअप अवसर</h1>
                <p><span class="badge">DATE: {date_str}</span></p>
                <p style="color: #7f8c8d; font-style: italic;">"India's Top 5 Problems vs Technology Solutions"</p>
            </div>
            
            {problem_blocks}

            <div style="background-color: #fff8e1; padding: 20px; border-radius: 8px; border: 1px dashed #ffa000; text-align: center;">
                <h3 style="margin-top: 0; color: #f57c00;">💡 BONUS: Quick Win Idea of the Day</h3>
                <p>Check the dashboard for micro-pivot opportunities!</p>
            </div>

            <div class="footer">
                <p>Generated by <strong>India Problem Scanner AI</strong> for Vikram Kumar Bosak</p>
                <p><em>Focus: Solving problems that Govt/NGOs can't.</em></p>
            </div>
        </div>
    </body>
    </html>
    """
    return html

def send_email(subject, html_content, to_email):
    """Sends the daily report via SMTP."""
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")
    
    if not sender_email or not sender_password:
        print("ERROR: Email credentials not set in .env")
        return False

    msg = MIMEMultipart("alternative")
    msg['From'] = f"India Problem Scanner Agent <{sender_email}>"
    msg['To'] = to_email
    msg['Subject'] = subject

    msg.attach(MIMEText(html_content, 'html', 'utf-8'))

    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        print(f"Email sent successfully to {to_email}")
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False

if __name__ == "__main__":
    # send_email("Test Subject", "Test Body", "user@example.com")
    print("Emailer ready.")
